# Gems
gems:
  - jekyll-paginate

# Site settings
# Add a value for `baseurl`, e.g. `/highlights` if you'd like to deploy from a subdirectory.
title: Highlights from books and articles | Melanie Richards
email: hello@melanie-richards.com
url: "http://highlights.melanie-richards.com"
baseurl:
images: /assets/images/content

# Blog settings
paginate: 10
paginate_path: "/all/page:num/"
permalink: "/book/:title/"

# Build settings
markdown: kramdown
sass:
  sass_dir: assets/_sass
  style: compressed

# Custom variable
twitter: "@somelaniesaid"
